export const IMAGES: Record<string, Record<string, Record<string, any>>> = {
    'africa': {
      'egypt': {
        'card1.jpg': require('../assets/countries/africa/egypt/card1.jpg'),
        'card2.jpg': require('../assets/countries/africa/egypt/card2.jpg'),
        'card3.jpg': require('../assets/countries/africa/egypt/card3.jpg'),
        'card4.jpg': require('../assets/countries/africa/egypt/card4.jpg'),
      },
      'morocco': {
        'card1.jpg': require('../assets/countries/africa/morocco/card1.jpg'),
        'card2.jpg': require('../assets/countries/africa/morocco/card2.jpg'),
        'card3.jpg': require('../assets/countries/africa/morocco/card3.jpg'),
        'card4.jpg': require('../assets/countries/africa/morocco/card4.jpg'),
        'card5.jpg': require('../assets/countries/africa/morocco/card5.jpg'),
      },
      'kenya': {
        'card1.jpg': require('../assets/countries/africa/kenya/card1.jpg'),
        'card2.jpg': require('../assets/countries/africa/kenya/card2.jpg'),
        'card3.jpg': require('../assets/countries/africa/kenya/card3.jpg'),
        'card4.jpg': require('../assets/countries/africa/kenya/card4.jpg'),
        'card5.jpg': require('../assets/countries/africa/kenya/card5.jpg'),
      },
    },
    'asia': {
      'japan': {
        'card1.jpg': require('../assets/countries/asia/japan/card1.jpg'),
        'card2.jpg': require('../assets/countries/asia/japan/card2.jpg'),
        'card3.jpg': require('../assets/countries/asia/japan/card3.jpg'),
        'card4.jpg': require('../assets/countries/asia/japan/card4.jpg'),
      },
      'china': {
        'card1.jpg': require('../assets/countries/asia/china/card1.jpg'),
        'card2.jpg': require('../assets/countries/asia/china/card2.jpg'),
        'card3.jpg': require('../assets/countries/asia/china/card3.jpg'),
        'card4.jpg': require('../assets/countries/asia/china/card4.jpg'),
      },
      'india': {
        'card1.jpg': require('../assets/countries/asia/india/card1.jpg'),
        'card2.jpg': require('../assets/countries/asia/india/card2.jpg'),
        'card3.jpg': require('../assets/countries/asia/india/card3.jpg'),
        'card4.jpg': require('../assets/countries/asia/india/card4.jpg'),
      },
      'indonesia': {
        'card1.jpg': require('../assets/countries/asia/indonesia/card1.jpg'),
        'card2.jpg': require('../assets/countries/asia/indonesia/card2.jpg'),
        'card3.jpg': require('../assets/countries/asia/indonesia/card3.jpg'),
        'card4.jpg': require('../assets/countries/asia/indonesia/card4.jpg'),
      },
      'thailand': {
        'card1.jpg': require('../assets/countries/asia/thailand/card1.jpg'),
        'card2.jpg': require('../assets/countries/asia/thailand/card2.jpg'),
        'card3.jpg': require('../assets/countries/asia/thailand/card3.jpg'),
        'card4.jpg': require('../assets/countries/asia/thailand/card4.jpg'),
        'card5.jpg': require('../assets/countries/asia/thailand/card5.jpg'),
      },
      'philippines': {
        'card1.jpg': require('../assets/countries/asia/philippines/card1.jpg'),
        'card2.jpg': require('../assets/countries/asia/philippines/card2.jpg'),
        'card3.jpg': require('../assets/countries/asia/philippines/card3.jpg'),
        'card4.jpg': require('../assets/countries/asia/philippines/card4.jpg'),
        'card5.jpg': require('../assets/countries/asia/philippines/card5.jpg'),
      },
      'singapore': {
        'card1.jpg': require('../assets/countries/asia/singapore/card1.jpg'),
        'card2.jpg': require('../assets/countries/asia/singapore/card2.jpg'),
        'card3.jpg': require('../assets/countries/asia/singapore/card3.jpg'),
        'card4.jpg': require('../assets/countries/asia/singapore/card4.jpg'),
        'card5.jpg': require('../assets/countries/asia/singapore/card5.jpg'),
      },
    },
    'europe': {
      'france': {
        'card1.jpg': require('../assets/countries/europe/france/card1.jpg'),
        'card2.jpg': require('../assets/countries/europe/france/card2.jpg'),
        'card3.jpg': require('../assets/countries/europe/france/card3.jpg'),
        'card4.jpg': require('../assets/countries/europe/france/card4.jpg'),
        'card5.jpg': require('../assets/countries/europe/france/card5.jpg'),
      },
      'germany': {
        'card1.jpg': require('../assets/countries/europe/germany/card1.jpg'),
        'card2.jpg': require('../assets/countries/europe/germany/card2.jpg'),
        'card3.jpg': require('../assets/countries/europe/germany/card3.jpg'),
        'card4.jpg': require('../assets/countries/europe/germany/card4.jpg'),
        'card5.jpg': require('../assets/countries/europe/germany/card5.jpg'),
      },
      'spain': {
        'card1.jpg': require('../assets/countries/europe/spain/card1.jpg'),
        'card2.jpg': require('../assets/countries/europe/spain/card2.jpg'),
        'card3.jpg': require('../assets/countries/europe/spain/card3.jpg'),
        'card4.jpg': require('../assets/countries/europe/spain/card4.jpg'),
        'card5.jpg': require('../assets/countries/europe/spain/card5.jpg'),
      },
      'italy': {
        'card1.jpg': require('../assets/countries/europe/italy/card1.jpg'),
        'card2.jpg': require('../assets/countries/europe/italy/card2.jpg'),
        'card3.jpg': require('../assets/countries/europe/italy/card3.jpg'),
        'card4.jpg': require('../assets/countries/europe/italy/card4.jpg'),
        'card5.jpg': require('../assets/countries/europe/italy/card5.jpg'),
      },
      'united-kingdom': {
        'card1.jpg': require('../assets/countries/europe/united-kingdom/card1.jpg'),
        'card2.jpg': require('../assets/countries/europe/united-kingdom/card2.jpg'),
        'card3.jpg': require('../assets/countries/europe/united-kingdom/card3.jpg'),
        'card4.jpg': require('../assets/countries/europe/united-kingdom/card4.jpg'),
        'card5.jpg': require('../assets/countries/europe/united-kingdom/card5.jpg'),
      },
      'greece': {
        'card1.jpg': require('../assets/countries/europe/greece/card1.jpg'),
        'card2.jpg': require('../assets/countries/europe/greece/card2.jpg'),
        'card3.jpg': require('../assets/countries/europe/greece/card3.jpg'),
        'card4.jpg': require('../assets/countries/europe/greece/card4.jpg'),
        'card5.jpg': require('../assets/countries/europe/greece/card5.jpg'),
      },
      'austria': {
        'card1.jpg': require('../assets/countries/europe/austria/card1.jpg'),
        'card2.jpg': require('../assets/countries/europe/austria/card2.jpg'),
        'card3.jpg': require('../assets/countries/europe/austria/card3.jpg'),
        'card4.jpg': require('../assets/countries/europe/austria/card4.jpg'),
        'card5.jpg': require('../assets/countries/europe/austria/card5.jpg'),
      },
      'switzerland': {
        'card1.jpg': require('../assets/countries/europe/switzerland/card1.jpg'),
        'card2.jpg': require('../assets/countries/europe/switzerland/card2.jpg'),
        'card3.jpg': require('../assets/countries/europe/switzerland/card3.jpg'),
        'card4.jpg': require('../assets/countries/europe/switzerland/card4.jpg'),
        'card5.jpg': require('../assets/countries/europe/switzerland/card5.jpg'),
      },
      'portugal': {
        'card1.jpg': require('../assets/countries/europe/portugal/card1.jpg'),
        'card2.jpg': require('../assets/countries/europe/portugal/card2.jpg'),
        'card3.jpg': require('../assets/countries/europe/portugal/card3.jpg'),
        'card4.jpg': require('../assets/countries/europe/portugal/card4.jpg'),
        'card5.jpg': require('../assets/countries/europe/portugal/card5.jpg'),
      },
      'turkey': {
        'card1.jpg': require('../assets/countries/europe/turkey/card1.jpg'),
        'card2.jpg': require('../assets/countries/europe/turkey/card2.jpg'),
        'card3.jpg': require('../assets/countries/europe/turkey/card3.jpg'),
        'card4.jpg': require('../assets/countries/europe/turkey/card4.jpg'),
        'card5.jpg': require('../assets/countries/europe/turkey/card5.jpg'),
      },
      'russia': {
        'card1.jpg': require('../assets/countries/europe/russia/card1.jpg'),
        'card2.jpg': require('../assets/countries/europe/russia/card2.jpg'),
        'card3.jpg': require('../assets/countries/europe/russia/card3.jpg'),
        'card4.jpg': require('../assets/countries/europe/russia/card4.jpg'),
        'card5.jpg': require('../assets/countries/europe/russia/card5.jpg'),
      },
      'netherlands': {
        'card1.jpg': require('../assets/countries/europe/netherlands/card1.jpg'),
        'card2.jpg': require('../assets/countries/europe/netherlands/card2.jpg'),
        'card3.jpg': require('../assets/countries/europe/netherlands/card3.jpg'),
        'card4.jpg': require('../assets/countries/europe/netherlands/card4.jpg'),
        'card5.jpg': require('../assets/countries/europe/netherlands/card5.jpg'),
      },
    },
    'northamerica': {
      'canada': {
        'card1.jpg': require('../assets/countries/northamerica/canada/card1.jpg'),
        'card2.jpg': require('../assets/countries/northamerica/canada/card2.jpg'),
        'card3.jpg': require('../assets/countries/northamerica/canada/card3.jpg'),
        'card4.jpg': require('../assets/countries/northamerica/canada/card4.jpg'),
        'card5.jpg': require('../assets/countries/northamerica/canada/card5.jpg'),
      },
      'panama': {
        'card1.jpg': require('../assets/countries/northamerica/panama/card1.jpg'),
        'card2.jpg': require('../assets/countries/northamerica/panama/card2.jpg'),
        'card3.jpg': require('../assets/countries/northamerica/panama/card3.jpg'),
        'card4.jpg': require('../assets/countries/northamerica/panama/card4.jpg'),
        'card5.jpg': require('../assets/countries/northamerica/panama/card5.jpg'),
      },
      'united-states': {
        'card1.jpg': require('../assets/countries/northamerica/unitedstates/card1.jpg'),
        'card2.jpg': require('../assets/countries/northamerica/unitedstates/card2.jpg'),
        'card3.jpg': require('../assets/countries/northamerica/unitedstates/card3.jpg'),
        'card4.jpg': require('../assets/countries/northamerica/unitedstates/card4.jpg'),
        'card5.jpg': require('../assets/countries/northamerica/unitedstates/card5.jpg'),
      },
      'mexico': {
        'card1.jpg': require('../assets/countries/northamerica/mexico/card1.jpg'),
        'card2.jpg': require('../assets/countries/northamerica/mexico/card2.jpg'),
        'card3.jpg': require('../assets/countries/northamerica/mexico/card3.jpg'),
        'card4.jpg': require('../assets/countries/northamerica/mexico/card4.jpg'),
        'card5.jpg': require('../assets/countries/northamerica/mexico/card5.jpg'),
      },
      'guatemala': {
        'card1.jpg': require('../assets/countries/northamerica/guatemala/card1.jpg'),
        'card2.jpg': require('../assets/countries/northamerica/guatemala/card2.jpg'),
        'card3.jpg': require('../assets/countries/northamerica/guatemala/card3.jpg'),
        'card4.jpg': require('../assets/countries/northamerica/guatemala/card4.jpg'),
        'card5.jpg': require('../assets/countries/northamerica/guatemala/card5.jpg'),
      },
      'dominican-republic': {
        'card1.jpg': require('../assets/countries/northamerica/dominicanrepublic/card1.jpg'),
        'card2.jpg': require('../assets/countries/northamerica/dominicanrepublic/card2.jpg'),
        'card3.jpg': require('../assets/countries/northamerica/dominicanrepublic/card3.jpg'),
        'card4.jpg': require('../assets/countries/northamerica/dominicanrepublic/card4.jpg'),
        'card5.jpg': require('../assets/countries/northamerica/dominicanrepublic/card5.jpg'),
      },
      'honduras': {
        'card1.jpg': require('../assets/countries/northamerica/honduras/card1.jpg'),
        'card2.jpg': require('../assets/countries/northamerica/honduras/card2.jpg'),
        'card3.jpg': require('../assets/countries/northamerica/honduras/card3.jpg'),
        'card4.jpg': require('../assets/countries/northamerica/honduras/card4.jpg'),
        'card5.jpg': require('../assets/countries/northamerica/honduras/card5.jpg'),
      },
      'nicaragua': {
        'card1.jpg': require('../assets/countries/northamerica/nicaragua/card1.jpg'),
        'card2.jpg': require('../assets/countries/northamerica/nicaragua/card2.jpg'),
        'card3.jpg': require('../assets/countries/northamerica/nicaragua/card3.jpg'),
        'card4.jpg': require('../assets/countries/northamerica/nicaragua/card4.jpg'),
        'card5.jpg': require('../assets/countries/northamerica/nicaragua/card5.jpg'),
      },
    },
    'oceania': {
      'australia': {
        'card1.jpg': require('../assets/countries/oceania/australia/card1.jpg'),
        'card2.jpg': require('../assets/countries/oceania/australia/card2.jpg'),
        'card3.jpg': require('../assets/countries/oceania/australia/card3.jpg'),
        'card4.jpg': require('../assets/countries/oceania/australia/card4.jpg'),
        'card5.jpg': require('../assets/countries/oceania/australia/card5.jpg'),
      },
      'new-zealand': {
        'card1.jpg': require('../assets/countries/oceania/new-zealand/card1.jpg'),
        'card2.jpg': require('../assets/countries/oceania/new-zealand/card2.jpg'),
        'card3.jpg': require('../assets/countries/oceania/new-zealand/card3.jpg'),
        'card4.jpg': require('../assets/countries/oceania/new-zealand/card4.jpg'),
        'card5.jpg': require('../assets/countries/oceania/new-zealand/card5.jpg'),
      },
      'fiji': {
        'card1.jpg': require('../assets/countries/oceania/fiji/card1.jpg'),
        'card2.jpg': require('../assets/countries/oceania/fiji/card2.jpg'),
        'card3.jpg': require('../assets/countries/oceania/fiji/card3.jpg'),
        'card4.jpg': require('../assets/countries/oceania/fiji/card4.jpg'),
        'card5.jpg': require('../assets/countries/oceania/fiji/card5.jpg'),
      }
    },
    'southamerica': {
      'argentina': {
        'card1.jpg': require('../assets/countries/southamerica/argentina/card1.jpg'),
        'card2.jpg': require('../assets/countries/southamerica/argentina/card2.jpg'),
        'card3.jpg': require('../assets/countries/southamerica/argentina/card3.jpg'),
        'card4.jpg': require('../assets/countries/southamerica/argentina/card4.jpg'),
        'card5.jpg': require('../assets/countries/southamerica/argentina/card5.jpg'),
      },
      'brazil': {
        'card1.jpg': require('../assets/countries/southamerica/brazil/card1.jpg'),
        'card2.jpg': require('../assets/countries/southamerica/brazil/card2.jpg'),
        'card3.jpg': require('../assets/countries/southamerica/brazil/card3.jpg'),
        'card4.jpg': require('../assets/countries/southamerica/brazil/card4.jpg'),
        'card5.jpg': require('../assets/countries/southamerica/brazil/card5.jpg'),
      },
      'chile': {
        'card1.jpg': require('../assets/countries/southamerica/chile/card1.jpg'),
        'card2.jpg': require('../assets/countries/southamerica/chile/card2.jpg'),
        'card3.jpg': require('../assets/countries/southamerica/chile/card3.jpg'),
        'card4.jpg': require('../assets/countries/southamerica/chile/card4.jpg'),
        'card5.jpg': require('../assets/countries/southamerica/chile/card5.jpg'),
      },
      'colombia': {
        'card1.jpg': require('../assets/countries/southamerica/colombia/card1.jpg'),
        'card2.jpg': require('../assets/countries/southamerica/colombia/card2.jpg'),
        'card3.jpg': require('../assets/countries/southamerica/colombia/card3.jpg'),
        'card4.jpg': require('../assets/countries/southamerica/colombia/card4.jpg'),
        'card5.jpg': require('../assets/countries/southamerica/colombia/card5.jpg'),
      },
      'peru': {
        'card1.jpg': require('../assets/countries/southamerica/peru/card1.jpg'),
        'card2.jpg': require('../assets/countries/southamerica/peru/card2.jpg'),
        'card3.jpg': require('../assets/countries/southamerica/peru/card3.jpg'),
        'card4.jpg': require('../assets/countries/southamerica/peru/card4.jpg'),
        'card5.jpg': require('../assets/countries/southamerica/peru/card5.jpg'),
      },
      'ecuador': {
        'card1.jpg': require('../assets/countries/southamerica/ecuador/card1.jpg'),
        'card2.jpg': require('../assets/countries/southamerica/ecuador/card2.jpg'),
        'card3.jpg': require('../assets/countries/southamerica/ecuador/card3.jpg'),
        'card4.jpg': require('../assets/countries/southamerica/ecuador/card4.jpg'),
        'card5.jpg': require('../assets/countries/southamerica/ecuador/card5.jpg'),
      },
      'bolivia': {
        'card1.jpg': require('../assets/countries/southamerica/bolivia/card1.jpg'),
        'card2.jpg': require('../assets/countries/southamerica/bolivia/card2.jpg'),
        'card3.jpg': require('../assets/countries/southamerica/bolivia/card3.jpg'),
        'card4.jpg': require('../assets/countries/southamerica/bolivia/card4.jpg'),
        'card5.jpg': require('../assets/countries/southamerica/bolivia/card5.jpg'),
      },
    },
  };
  